CREATE DATABASE Tienda;
USE Tienda;


CREATE TABLE PRODUCTO (
	codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre_producto VARCHAR(50) NOT NULL,
    existencias_producto INT(8) NOT NULL,
    precio_venta_producto DECIMAL(5,2) NOT NULL,
    costo_producto DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY(codigo)
);

DROP TABLE PRODUCTO;

SELECT * FROM PRODUCTO ORDER BY nombre_producto;
ALTER TABLE PRODUCTO RENAME COLUMN precio_venta_producto TO costo_producto;
UPDATE PRODUCTO SET existencias_producto = existencias_producto - 1 WHERE codigo = '001ASACH';
SELECT * FROM PRODUCTO ORDER BY codigo;
DELETE FROM PRODUCTO;
SELECT COUNT(*) AS productos FROM PRODUCTO;

UPDATE PRODUCTO SET nombre_producto = "";

CREATE TABLE COTIZACIONES(
	id INT UNIQUE NOT NULL AUTO_INCREMENT,
    fecha LONGTEXT NOT NULL,
    hora LONGTEXT NOT NULL,
    codigos LONGTEXT NOT NULL,
    productos LONGTEXT NOT NULL,
    cantidades LONGTEXT NOT NULL,
    precios LONGTEXT NOT NULL,
    totales LONGTEXT NOT NULL,
    descuento decimal(5, 2) NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE COTIZACIONES;

SELECT * FROM COTIZACIONES;
DELETE FROM COTIZACIONES;

SELECT * FROM COTIZACIONES WHERE id = 2;

CREATE TABLE DEVOLUCIONES (
	id INT UNIQUE NOT NULL AUTO_INCREMENT,
    fecha LONGTEXT NOT NULL,
    hora LONGTEXT NOT NULL,
    codigos LONGTEXT NOT NULL,
    productos LONGTEXT NOT NULL,
    cantidades LONGTEXT NOT NULL,
    precios LONGTEXT NOT NULL,
    totales LONGTEXT NOT NULL,
    PRIMARY KEY(id)
);
SELECT * FROM DEVOLUCIONES;

SHOW TABLES;